### ISSUE TITLE
V3: Filter On Manual Import

### ISSUE THREAD

**Issue by Eleniatari** [Whisparr/Whisparr#178]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Once the list of scenes gets long enough. Searching by name causes significant delay and lag between typing each character and the list refreshing. Sometimes 3-4 seconds while the list filters itself.

### Describe the solution you'd like

Have the ability to narrow the list initially by selecting a studio or year to help prevent the search lag.

### Describe alternatives you've considered

None that would not require a major rework.

**Comment by plz12345** [comment]
What about just limiting this view to 100 items by default and onChange for the text box?  The filter would re-fetch based on all items, but only display a max of 100.  I believe the performance hit you see is the web content re-rendering.

**Comment by Eleniatari** [comment]
That is the case it appears. As scenes go up the lag gets longer. It would definitely help. It may need some form of 'more' function though.

**Comment by plz12345** [comment]
OK, so this is happening in SelectMovieModalContent.tsx

``` javascript
  const items = useMemo(() => {
    const sorted = [...allMovies].sort((a, b) =>
      a.sortTitle.localeCompare(b.sortTitle)
    );

    return sorted.filter(
      (item) =>
        item.title.toLowerCase().includes(filter.toLowerCase()) ||
        item.tmdbId.toString().includes(filter) ||
        item.imdbId?.includes(filter)
    );
  }, [allMovies, filter]);
```

It's not very efficient when working with a large data set, as it's drawing the entire movie table into the page JavaScript and then filtering it in-browser, vs. doing a WHERE/LIKE query on the database.  This only appears to get sluggish with quite large libraries, and that is likely also tied to browser performance.

Something like below, so the filter is doing precision matches on those ID's rather than an `includes`.  Also using `sortTitle` removes the need to force the entire array's `title` property to lowercase, since it's stored that way already.  I tested this on a library with about 10K scenes and really didn't notice a difference in performance, though.

``` javascript
      (item) =>
        item.sortTitle.includes(filter.toLowerCase()) ||
        item.tmdbId?.toString() === filter ||
        item.imdbId?.toString() === filter
```

Can we remove the `imdbId` filter entirely, since that's not actually used in V3?

Additionally, maybe we add a conditional logic before firing the onChange to only trigger if the filter is 3+ characters?  We could also add a delay of 1000-1500ms if the library size is over  a certain high threshold like 50K.

**Comment by Eleniatari** [comment]
Will this solve the issue where a leading or following space can defeat the search as well?

**Comment by plz12345** [comment]
> Will this solve the issue where a leading or following space can defeat the search as well? 

I wasn't aware that was an issue but  can add a string trim to the logic.

**Comment by Eleniatari** [comment]
It was part of the special character request that got closed with no comment. It got skipped over like most of it.

Special characters still don't work.

**Comment by plz12345** [comment]
> It was part of the special character request that got closed with no comment. It got skipped over like most of it.
> 
> 
> 
> Special characters still don't work. 

The manual import filter is doing it on "clean title" which has no special characters. I'll look at adding the same character stripping to that text input that gets used to create that clean title.

**Comment by Eleniatari** [comment]
All good. Even the scene search can't handle it. Basicly anywhere you can input text can't hand special characters.

**Comment by plz12345** [comment]
> All good. Even the scene search can't handle it. Basicly anywhere you can input text can't hand special characters. 

It's because they use a "contains" function comparing your input to a column that will never contain those characters.
