### ISSUE TITLE
V3: JSON call is too large out of memory to parse and all the information

### ISSUE THREAD

**Issue by LanceMagnaye26** [Whisparr/Whisparr#209]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When going to the Scenes page, I get the following error: **UnableToLoadScenes**

![Screenshot 2024-03-28 134303](https://github.com/Whisparr/Whisparr/assets/32000484/0d815ade-5d08-4308-a128-cee56490cca1)

JSON call is around 500MB
![Screenshot 2024-03-28 144641](https://github.com/Whisparr/Whisparr/assets/32000484/017bda5f-7b9d-4739-9f80-21418e96bfad)

Before API Call
![Screenshot 2024-03-28 153701](https://github.com/Whisparr/Whisparr/assets/32000484/12ecb155-2fe4-4a93-a75b-3abd5d525f2e)

After API Call
![Screenshot 2024-03-28 153726](https://github.com/Whisparr/Whisparr/assets/32000484/47bd15fe-a6fa-4bdb-adad-6b98f3973db1)

### Expected Behavior

Scenes show up

### Steps To Reproduce

Go into scenes tab

### Environment

```markdown
- OS: Unraid 
- Whisparr:
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Google Chrome
- Database: Sqlite
```

### What branch are you running?

Main

### Trace Logs?

Couldn't paste as it was over the character limit.

https://justpaste.it/asl2p

**Comment by sampulsar** [comment]
@plz12345 
Whisparr V3 is a fork of Radarr, so would not want to drastically change the client so it still can get updates from Radarr via a merge. Radarr likely would not hit this issue as you would need a large number of movies.

Suggestion is to create a new set of API methods one that gets all of the movies like the existing one but with limited fields, maybe just the ids, and none metadata information. Then another gets the metadata information in for a batch of the ids, needs to be a post so that say 10,000 ids can be passed.

The FE will then have to do this in change the code so it can do it in two stages and return the data. Nothing else in the client then needs to change, as the data can be the same.

export const actionHandlers = handleThunks({

  **[FETCH_MOVIES]: createFetchHandler(section, '/movie'),**

I can have a play
