### ISSUE TITLE
Search Function Appears Broken

### ISSUE THREAD

**Issue by Protektor-Desura** [Whisparr/Whisparr#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I search for Emmanuelle nothing shows up.

### Expected Behavior

I should see 20+ movies.

### Steps To Reproduce

You can see here how many movies should show up.
https://www.themoviedb.org/search?language=en-US&query=Emmanuelle

### Environment

```markdown
- OS: Docker
- Whisparr: 0.1.0.49
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome & Firefox
```

### What branch are you running?

Nightly

### Trace Logs?

N/A

**Comment by Protektor-Desura** [comment]
I think there is a problem with the search function. I'm not seeing movies that I know TMDB has in their database. Both in search terms, specific movies, and searching for directors.

https://www.themoviedb.org/search/movie?language=en-US&page=4&query=Emmanuelle
https://www.themoviedb.org/movie/5725-supervixens?language=en-US
https://www.themoviedb.org/person/4590-russ-meyer?language=en-US
https://www.themoviedb.org/person/58021-tinto-brass?language=en-US
https://www.themoviedb.org/movie/315-faster-pussycat-kill-kill?language=en-US
https://www.themoviedb.org/movie/9453-caligola?language=en-US

**Comment by bakerboy448** [comment]
Related to https://github.com/Whisparr/Whisparr/issues/20

"N/A" for is not valid for bug reports for logs....

**Comment by bakerboy448** [comment]
https://www.themoviedb.org/movie/53664-emmanuelle-2000-emmanuelle-in-paradise  Is a radarr addition, not whisparr

**Comment by Protektor-Desura** [comment]
If I can do a proper search for known porn movies in TMDB then that is a bug. I don't understand what you are saying. I'm showing information that is in TMDB but I can't get it to import or use inside Whisparr.

If I go to add movie and put in:
tmdb:53664
and it does NOT find it to add then that is a bug and something is broken. Because it is porn.

**Comment by ninjamonkey198206** [comment]
When did TMDb add the default setting to block adult content when logged into their site?
I know Jack about how this all works, just something I came across today trying to figure this exact issue out.

**Comment by austinwbest** [comment]
@ninjamonkey198206  Adult off by default has always been that way for user accounts to my knowledge.

@Protektor-Desura i think you're missing a fundamental part. Baker said they are Radarr items because they are. If it is not flagged as `Adult` then it goes in Radarr. If it is flagged as `Adult` then it goes in Whisparr. So you simply need to edit the movies on TMDb and if they are adult movies, mark them as such (i believe users can do that)

This is Radarr
![image](https://user-images.githubusercontent.com/8321115/188486537-dbadae40-38ff-41d2-b6ba-2cfa3039d8a9.png)

This is Whisparr
![image](https://user-images.githubusercontent.com/8321115/188486571-cc80a4c3-337e-45f7-b450-78278c1d66d6.png)

If you can find an item flagged as `Adult` and not found by Whisparr then there would possibly be a bug (if it isn't a cache issue) but for the things listed here, this is not a bug. Having other meta sources will also help alleviate this kind of thing as another meta source would have likely picked it up as well which is what the issue he linked aims to solve.

**Comment by ninjamonkey198206** [comment]
https://www.themoviedb.org/movie/513406-star-wars-the-last-temptation-parody

![Screenshot_20220905-112622_Chrome](https://user-images.githubusercontent.com/24654529/188489458-95a4d2ce-48d7-4d2a-acc2-8a78981fe785.jpg)

![Screenshot_20220905-113017_Chrome](https://user-images.githubusercontent.com/24654529/188489739-3a272057-c18c-4774-98aa-9bc9495958ba.jpg)
![Screenshot_20220905-113047_Chrome](https://user-images.githubusercontent.com/24654529/188489767-af65d4c2-a837-4fee-bf32-12c7582330b6.jpg)

This was working not too long ago, then suddenly stopped.

Something is wrong, I'm just not sure exactly where. I don't see anything in my firewall or HAProxy logs indicating an issue with either of those.

**Comment by austinwbest** [comment]
You are not the only one getting that unable to communicate with tmdb error. That isn't the same as this issue though.

**Comment by ninjamonkey198206** [comment]
Ah, ok. Also can't import movies due to this either. Whatever the cause is, it's borking the whole thing.
