### ISSUE TITLE
Automatic Update option

### ISSUE THREAD

**Issue by MrMxyzptlk** [Whisparr/Whisparr#51]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

N/A

### Describe the solution you'd like

I have over 15,000 movies in Whisparr; they are ALL full movies not scenes.
How do I turn off automatic updates?

I read that the upcoming changes will switch to scenes only to start; I do not want this to happen to my collection.
If I can disable updates on my current instance, I will just install a 2nd instance for scenes until this gets 'combined'.

Thank you for your hard ; > work! 

### Describe alternatives you've considered

N/A

**Comment by thezak48** [comment]
How to stay on v1
Due to the recent major metadata change Whisparr now supports scenes, however this means quite a large change in data structure and code base and as such Whisparr v1 databases will not be supported in Whisparr v2. On install v2 will create a new DB titled Whisparr2.db (while leaving the old intact).

If you want to stay on v1 or keep a v1 instance running then you will need to change the branch name to v1

**Comment by MrMxyzptlk** [comment]
Thank you, that is awesome.
